In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("/content/sample_data/california_housing_train.csv")

In [4]:
df.head(1)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0

In [10]:
data ={
    "Employee":["Tushar", "Shweta", "Aditya", "Shreya", "Nayan"],
    "Department":["HR", "IT","Finance","Marketing", "Sales"],
    "Salary":[50000,55000,45000,60000,65000]}

In [13]:
df = pd.DataFrame(data, index = ["EMP01","EMP02","EMP03","EMP04","EMP05"])

In [14]:
df

      Employee Department  Salary
EMP01   Tushar         HR   50000
EMP02   Shweta         IT   55000
EMP03   Aditya    Finance   45000
EMP04   Shreya  Marketing   60000
EMP05    Nayan      Sales   65000

In [17]:
df.loc['EMP03']        #loc = location of index

Employee       Aditya
Department    Finance
Salary          45000
Name: EMP03, dtype: object

In [22]:
df.loc[['EMP01','EMP02']]

      Employee Department  Salary
EMP01   Tushar         HR   50000
EMP02   Shweta         IT   55000

In [25]:
df.iloc[2]        #index location

Employee       Aditya
Department    Finance
Salary          45000
Name: EMP03, dtype: object

In [33]:
df['Bonus'] = df['Salary'] * 0.1

In [34]:
df

      Employee Department  Salary   Bonus
EMP01   Tushar         HR   50000  5000.0
EMP02   Shweta         IT   55000  5500.0
EMP03   Aditya    Finance   45000  4500.0
EMP04   Shreya  Marketing   60000  6000.0
EMP05    Nayan      Sales   65000  6500.0

In [35]:
new_df = df.where(df['Salary']>60000)

In [36]:
new_df

      Employee Department   Salary   Bonus
EMP01      NaN        NaN      NaN     NaN
EMP02      NaN        NaN      NaN     NaN
EMP03      NaN        NaN      NaN     NaN
EMP04      NaN        NaN      NaN     NaN
EMP05    Nayan      Sales  65000.0  6500.0

In [41]:
df['Salary_Catagory'] = pd.cut(df['Salary'],bins=[40000,50000,60000,70000],labels=['low','medium','high'])

#it use for feature engg. that mean to convert numerical feature to categorical.
#bins=[0,18,32,60,100].
#labels = ['tean', 'adut', 'senior','old']

In [42]:
df

      Employee Department  Salary   Bonus Salary_Catagory
EMP01   Tushar         HR   50000  5000.0             low
EMP02   Shweta         IT   55000  5500.0          medium
EMP03   Aditya    Finance   45000  4500.0             low
EMP04   Shreya  Marketing   60000  6000.0          medium
EMP05    Nayan      Sales   65000  6500.0            high

In [44]:
df[['Salary' , 'Bonus']].describe()

            Salary        Bonus
count      5.00000     5.000000
mean   55000.00000  5500.000000
std     7905.69415   790.569415
min    45000.00000  4500.000000
25%    50000.00000  5000.000000
50%    55000.00000  5500.000000
75%    60000.00000  6000.000000
max    65000.00000  6500.000000

In [45]:
df['Salary'].mean()

55000.0

In [47]:
df['Salary'].median()

55000.0

In [58]:
df['Salary_Catagory'].mode()

0       low
1    medium
Name: Salary_Catagory, dtype: category
Categories (3, object): ['low' < 'medium' < 'high']

In [54]:
#df.groupby()[]

#always use 1st paranthesis & 2nd square braces.

#always use when you need more than one column calculation.

#for more than 2 column pass list in paranthesis.

#in square braces output feature or numerical is use.

In [59]:
df.groupby('Salary_Catagory')['Salary'].mean()

<ipython-input-59-0b3baa202064>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Salary_Catagory')['Salary'].mean()

Salary_Catagory
low       47500.0
medium    57500.0
high      65000.0
Name: Salary, dtype: float64

In [62]:
df.groupby(['Salary_Catagory','Department'])['Salary'].mean()

<ipython-input-62-7a47a79ba8dd>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['Salary_Catagory','Department'])['Salary'].mean()

Salary_Catagory  Department
low              Finance       45000.0
                 HR            50000.0
                 IT                NaN
                 Marketing         NaN
                 Sales             NaN
medium           Finance           NaN
                 HR                NaN
                 IT            55000.0
                 Marketing     60000.0
                 Sales             NaN
high             Finance           NaN
                 HR                NaN
                 IT                NaN
                 Marketing         NaN
                 Sales         65000.0
Name: Salary, dtype: float64

In [63]:
df.groupby(['Salary_Catagory','Department'])['Salary'].mean().unstack()

<ipython-input-63-75339bccb992>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['Salary_Catagory','Department'])['Salary'].mean().unstack()

Department       Finance       HR       IT  Marketing    Sales
Salary_Catagory
low              45000.0  50000.0      NaN        NaN      NaN
medium               NaN      NaN  55000.0    60000.0      NaN
high                 NaN      NaN      NaN        NaN  65000.0

In [64]:
import seaborn as sns

In [65]:
df1 = sns.load_dataset("titanic")

In [66]:
df1

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [67]:
df1.shape

(891, 15)

In [69]:
df1['sex'].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [71]:
df1['survived'].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [73]:
df1.groupby('sex')['survived'].value_counts().unstack()

survived    0    1
sex
female     81  233
male      468  109

In [78]:
df1['survived'].value_counts(normalize = True)*100                                                       #normalize (percentage)

survived
0    61.616162
1    38.383838
Name: proportion, dtype: float64